spring:
  application:
    name: AvroTest
  data:
    mongodb:
      uri: mongodb+srv://boris:qwe321@cluster0-bp4qe.mongodb.net/myFirstDB

logging:
  level:
    boris: DEBUG

avroTest:
  kafka:
    bootstrapServers: localhost:29092
    zkServers: localhost:32181
    schemaRegistry: http://localhost:8081
    topic: borisTest
    streams:
      applicationId: avroTest1