node  {

	stage('start') {
		echo 'Starting pipeline triggered by git'
	}
	
	stage('clone repository') {
		checkout scm
	}
	
	stage('build project') {
		dir('Avro Test') {
	    	sh './gradlew clean build test'
	    }
	}
}