pipeline {
    agent any
    stages {
        stage('build') {
        	steps {
	    	    echo 'Starting pipeline'
	    	    echo 'Starting pipeline Again'
	    	    git url: 'https://github.com/b-liberman/avro_test.git'
    	    }
        }
    }
}
